### ISSUE TITLE
Sadetutkan pixelien läpi ei meinaa nähdä karttaa

### ISSUE THREAD

**Issue by suihkulokki** [heikkipora/sataako-fi#1]
![tutkakuva](http://i.imgur.com/ketZ40z.png)

Hiukan enemmän opacityä voisi olla jees - toki nykyiselläkin vastaus on aika selkeä "sataa" :)

**Comment by heikkipora** [comment]
Pistin 10 prosenttiyksikköä läpinäkyvämmäksi :)  Kovin paljoa ei voi säätää tai heikommat sateet ei erotu ollenkaan
