### ISSUE TITLE
OpenStreetMap/Mapbox attribution

### ISSUE THREAD

**Issue by theel0ja** [heikkipora/sataako-fi#14]
The website seems to use Mapbox's tiles, but you forgot attribution.

https://www.mapbox.com/help/how-attribution-works/

**Comment by heikkipora** [comment]
You are absolutely right. I left those out for aesthetic reasons - but that is naturally not the right way.

Thanks for giving me the required push :-) - https://www.sataako.fi now shows attributions properly!

**Comment by theel0ja** [comment]
Great!

However, that sidebar is on top of that attribution.

**Comment by heikkipora** [comment]
..which you can (and should) naturally close after seeing it once. The map is not really visible for most of the users (on mobile) at that stage so I'm not that concerned about it (the attribution) being hidden as well.
