### ISSUE TITLE
Add lightning counter if data available

### ISSUE THREAD

**Issue by huuhaa** [heikkipora/sataako-fi#44]
It would be great if lightning feature #17 could be improved with something similar as following:

1) Ability to either set radar as distance (km) for selected location In this case that circle should be shown), or just all data for curent zoomlevel and....

2) Show both, lighning counts at the next of lightning symbols for the group of lighnings (one counter for bigger group, maybe own counter if repeatedly lightnings at one location) + possibility to see static summary of selected area (either that radar from current location, or the whole area shown at current zomlevel.

Sure this idea has a room for improvements, but main thing is that lighning counter would be nice to have feature too.

**Comment by heikkipora** [comment]
Thanks for the suggestion! However, I don't think this will get implemented - as I try to keep the features (and amount of code) at a minimum. In my view, the sataako.fi user base would not benefit from - nor need/use those statistics.
