### ISSUE TITLE
Possible to change using MapLibre?

### ISSUE THREAD

**Issue by huuhaa** [heikkipora/sataako-fi#45]
Would it be possible to change site to use MapLibre instead of MapBox?

https://github.com/maplibre

Why even asking?

Platforms with improved privacy protection ( either being de-googled Android, like LeOS GSI etc. browsers like LibreWolf or Mull at mobile ) won't currently show map at all. I'm not exactly sure what is causing this, but since MapBox is nowdays detected as tracker, I suppose this is main cause behind this. Also asked from LeOS dev who did say LeOS won't work with MapBox & has removed a lot google calls from system too, so using those could also cause some issues.

Anyway, if possible and even close as "drop in replacement" to switch using MapLibre, it would be great to use this site on privacy focused systems too.

**Comment by heikkipora** [comment]
The site actually uses OpenStreetMap tiles rendered with OpenLayers - so no MapBox integration is in place nowadays.
However, README.md in this repository incorrectly stated that MapBox tiles are being used which has not been the case for some years now.

I updated the README.md to reflect the current state of affairs.
